template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "mans1258"
__REPO__ = "lang-mns"
__UND2C__ = "mns"
__UNDEFINED__ = "Mansi"
__UND__ = "mns"
