template = "https://github.com/giellalt/template-lang-und"
rev_id = 194
template_sha = "d9f8684d6c538483961839ae9a832726cdfd811b"

[replacements]
__REPO__ = "lang-mns"
__UND2C__ = "mns"
__UNDEFINED__ = "Mansi"
__UND__ = "mns"
